# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: LevelUp
lang: en
timezone: America/Los_Angeles
description: > # this means to ignore newlines until "baseurl:"
  This is a blog and/or wiki for Central App Dev to share knowledge with each other.
url: https://pennymac.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /levelup # the subpath of your site, e.g. /blog
permalink: /:title

gems:
  - jekyll-autoprefixer
  - jekyll-feed

safe: false

sass:
  style: compressed

# Set Jekyll's env to enable/disable Uglifier    
env: 'production'  


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

stitch:
  dependencies: 
    - 'assets/javascripts/site.js'
  output: 'assets/javascripts/application.min.js'
  fingerprint: false
  cleanup: true
  uglify: true
  uglify_options: {}